baseURL = "https://southside.chillers.online/"
languageCode = "en-us"
title = "Southside Chillers"
theme = "ghostwriter"

[params]
  description = " "
  copyright = " "
  shareFacebook = false
  shareTwitter = false
  shareGooglePlus = false
  shareLinkedIn = false
